### PR TITLE
Enhance Search Functionality with Debouncing, Error Handling, and Video Player Resizing

### PR DESCRIPTION
**Pull request by nisargpro**
**Debounced search, error handling, video resize, and stable Flutter.**
This condensed version still conveys the key points:

- Search improvements (debouncing implies smoother experience)
- Error handling for robustness
- Video player size control for flexibility
- Upgraded to a stable Flutter version

### CODE REVIEW

**Review by kananinirav — APPROVED** [review]
@nisargpro Thanks for PR 🙏 🙇

**Comment by nisargpro** [comment]
> @nisargpro Thanks for PR 🙏 🙇

you are welcome. it is a really good project, will be making more improvements on the go

**Comment by kananinirav** [comment]
@nisargpro  I'm still new to Flutter 😄, so I'm open to any suggestions for improvement.

I have an idea for a new feature: displaying channel groups on the home screen along with the list of channels within each group. To implement this, we just need to add one more property to the `Channel` model and retrieve data from the `ChannelsProvider`.

For example:

```m3u
#EXTINF:-1 group-title="News" tvg-logo="https://i.ibb.co/8sVYKmM/IMG-20240126-084123.jpg",Jamuna TV
```

We'll extract the group-title property and use it for grouping.

**Comment by nisargpro** [comment]
> @nisargpro I'm still new to Flutter 😄, so I'm open to any suggestions for improvement.
> 
> I have an idea for a new feature: displaying channel groups on the home screen along with the list of channels within each group. To implement this, we just need to add one more property to the `Channel` model and retrieve data from the `ChannelsProvider`.
> 
> For example:
> 
> ```
> #EXTINF:-1 group-title="News" tvg-logo="https://i.ibb.co/8sVYKmM/IMG-20240126-084123.jpg",Jamuna TV
> ```
> 
> We'll extract the group-title property and use it for grouping.

that is really a good improvement let me check how the UI will look in that sense.

**Comment by kananinirav** [comment]
> that is really a good improvement let me check how the UI will look in that sense. We can have cards with the categories and on clicked will open the filtered channels.

Or we can add a new screen to display all the channel groups. Then, when a group is clicked, we can display the channels within that group, similar to the current home screen functionality.

**Pull request merged**
